apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ml-image-compare.fullname" . }}
  labels:
    app: {{ template "ml-image-compare.name" . }}
    chart: {{ template "ml-image-compare.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ml-image-compare.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ml-image-compare.name" . }}
        release: {{ .Release.Name }}
        author: {{ .Values.author | default "Unknown solder" | replace " " "_" | replace "noshell-" "" | quote }}
        buildno: {{ .Values.buildno | default "Unknown" | replace "noshell-" "" | quote }}
        commitid: {{ .Values.commitid | default "local" | replace "noshell-" "" | quote }}
        version: {{ .Values.version | default "local" | replace "noshell-" "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ .Values.secret.path }}/secret.json
          {{- range $k, $v := .Values.pubsub }}
          - name: {{ $k }}
            value: {{ $v }}
          {{- end }}
          volumeMounts:
          - name: creds
            mountPath: {{ .Values.secret.path }}
            readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: creds
        secret:
          secretName: {{ template "ml-image-compare.fullname" . }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
