apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ml-image-compare.fullname" . }}
  labels:
    app: {{ template "ml-image-compare.name" . }}
    release: {{ .Release.Name }}
data:
  secret.json: {{ .Values.secret.data }}
